model: 'MACE'
foundation_model: 'mace-suite/foundation_model/MACE-OFF23_medium.model'
multiheads_finetuning: True
name: 'thymine_md'
model_dir: 'mace-suite/runs/thymine/combined/models'
log_dir: 'mace-suite/runs/thymine/combined/logs'
results_dir: 'mace-suite/runs/thymine/combined/results'
device: cuda
heads:
  spin_flip_es1:
    train_file: 'mace-suite/data/processed_datasets/thymine/combined/train_es1.xyz'
    valid_file : 'mace-suite/data/processed_datasets/thymine/combined/validation_es1.xyz'
    energy_key: 'REF_energy'
    forces_key: 'REF_forces'
    E0s: 'isolated'
  spin_flip_es2:
    train_file: 'mace-suite/data/processed_datasets/thymine/combined/train_es2.xyz'
    valid_file : 'mace-suite/data/processed_datasets/thymine/combined/validation_es2.xyz'
    energy_key: 'REF_energy'
    forces_key: 'REF_forces'
    E0s: 'isolated'

pt_train_file: 'mace-suite/data/pretrained_datasets/cleaned/cleaned_pt_train.xyz'
max_num_epochs: 700
start_swa: 475
batch_size: 5
seed: 42
