model: 'MACE'
foundation_model: 'mace-suite/foundation_model/MACE-OFF23_medium.model'
multiheads_finetuning: False
name: 'oxirane_raw'
model_dir: 'mace-suite/runs/oxirane/raw/models'
log_dir: 'mace-suite/runs/oxirane/raw/logs'
results_dir: 'mace-suite/runs/oxirane/raw/results'
device: cuda
heads:
  spin_flip_es1:
    train_file: 'mace-suite/data/processed_datasets/oxirane/isolated/train_oxirane_sf-es1.xyz'
    valid_file : 'mace-suite/data/processed_datasets/oxirane/isolated/validation_oxirane_sf-es1.xyz'
    energy_key: 'REF_energy'
    forces_key: 'REF_forces'
    E0s: 'isolated'
  spin_flip_es2:
    train_file: 'mace-suite/data/processed_datasets/oxirane/isolated/train_oxirane_sf-es2.xyz'
    valid_file : 'mace-suite/data/processed_datasets/oxirane/isolated/validation_oxirane_sf-es2.xyz'
    energy_key: 'REF_energy'
    forces_key: 'REF_forces'
    E0s: 'isolated'

max_num_epochs: 700
start_swa: 475
batch_size: 5
seed: 42
